#!/usr/bin/env bash
set -e

die() {
  echo $@ >&2
  exit 1
}

query() {
    echo "$JSON" | jq -r "$1"
}

cmd() {
    echo -e "\e[97m:: $@\e[0m" >&2
    echo -e "\e[90m" >&2
    
    RESULT="$(exec $@)" >&2

    echo "${RESULT}" >&2
    echo -e "\e[0m" >&2

    echo "${RESULT}"
}

run() {
    echo -e "\e[97m:: $@\e[0m" >&2
    echo -e "\e[90m" >&2

    $@ >&2

    echo -e "\e[0m" >&2
}

JSON="$(cmd gh repo view --json 'id,url')"
CURRENT_REPO_ID="$(query '.id')"
CURRENT_REPO_URL="$(query '.url')"

JSON="$(cmd gh pr view --json 'baseRefName,headRefName,mergeable,state,isDraft,number,headRepository,headRepositoryOwner,url' $@)"
NUMBER="$(query '.number')"
URL="$(query '.url')"
BASE_REF="$(query '.baseRefName')"
HEAD_REF="$(query '.headRefName')"
HEAD_REPO_ID="$(query '.headRepository.id')"
HEAD_REPO_OWNER="$(query '.headRepositoryOwner.login')"
IS_DRAFT="$(query '.isDraft')"
MERGEABLE="$(query '.mergeable')"
STATE="$(query '.state')"

if ! echo "${URL}" | grep -q "${CURRENT_REPO_URL}"; then
    die "ERROR: Current working directory is not the repository to merge into."
fi

if [ $STATE != "OPEN" ]; then
    die "ERROR: The pull request is no longer opened."
fi

if [ $MERGEABLE != "MERGEABLE" ]; then
    die "ERROR: Resolving conflicts is needed to continue the merge."
fi

if [ $IS_DRAFT == "true" ]; then
    die "ERROR: The pull request is draft."
fi

BASE_REPO_ID="${CURRENT_REPO_ID}"
ORIGIN="origin"

if [ $BASE_REPO_ID != $HEAD_REPO_ID ]; then
    JSON="$(cmd gh repo view --json 'url' "${HEAD_REPO_ID}")"
    HEAD_REPO_URL="$(query '.url')"
    UPSTREAM="upstream"

    git remote add "${ORIGIN}" "${HEAD_REPO_URL}"
else
    UPSTREAM="${ORIGIN}"
fi

CURRENT_BRANCH="$(cmd git branch --show-current)"

# First, fetches changes from the origin and the upstream.
run git fetch "${UPSTREAM}"
run git fetch "${ORIGIN}"

# Next, switches to the base branch, then merges the head branch.
run git checkout "${ORIGIN}/${BASE_REF}"
run git merge --no-ff "${UPSTREAM}/${HEAD_REF}"
run git commit --amend -F - <<EOS
Merge branch #${NUMBER} from ${HEAD_REPO_OWNER}/${HEAD_REF}
X-Committed-Using: https://github.com/siketyan/gh-smerge
EOS

# And push to the origin.
run git push "${ORIGIN}" "HEAD:${BASE_REF}"

# Lastly pop the working branch.
run git checkout "${CURRENT_BRANCH}"
